#!/usr/bin/bash
echo "gitt 1.0"
echo " ********************* pulling "
git pull
echo adding
git add .
echo " ********************* committing..."
git commit -m "committing"

git status
git checkout
echo " ******************** pushing..."
git push
