######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 4 16:57:57 2007
######################################################################
QT += gui core sql widgets
TEMPLATE = app
TARGET = ap
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
HEADERS += advexpdelegate.h exphelper.h treedialog.h
FORMS += treedialog.ui
SOURCES += advexpdelegate.cpp exphelper.cpp main.cpp treedialog.cpp
