#!/bin/bash

echo ---------------------------------------------- APT_GET UPDATE
sudo apt-get update
echo sistem yenilendi ----------------------------------------------



filename01="/usr/share/lightdm/lightdm.conf.d/01_myconf"
filename02="/etc/pulse/daemon.conf"
set -e

function checker() { 
        which "$1" | grep -o "$1" > /dev/null &&  return 0 || return 1 
}



function 01_myconf()
{
if [ -f "$filename01" ];
then

echo "Dosya Var - /usr/share/lightdm/lightdm.conf.d/01_myconf"
else
echo "Dosya yok - /usr/share/lightdm/lightdm.conf.d/01_myconf"
echo creating /usr/share/lightdm/lightdm.conf.d/01_myconf  

touch myconfx
echo [SeatDefaults] >> myconfx
echo greeter-hide-users=false >> myconfx
echo allow-guest=false >> myconfx
echo  >> myconfx
#echo #user-session=Xfce Oturumu  >> $filename01
#echo #greeter-session=LightDM GTK+ Greeter >> $filename01
echo  >> myconfx
echo [Seat:*] >> myconfx
echo autologin-user=murat >> myconfx
echo autologin-user-timeout=60 >> myconfx
sudo cp -i myconfx /usr/share/lightdm/lightdm.conf.d/01_myconf
echo Dosya oluşturuldu - /usr/share/lightdm/lightdm.conf.d/01_myconf
echo ----------------------------------
fi
echo ---------------------------------------------------------------
echo ---------------------------------------------------------------
echo /usr/share/lightdm/lightdm.conf.d/01_myconf 
echo --------------------/usr/share/lightdm/lightdm.conf.d/01_myconf 
cat $filename01
echo ---------------------------------------------------------------
echo ---------------------------------------------------------------
}


function daemonconf()
{
echo ************************************************************** 2 
if [ -f "$filename02" ];
then
echo "Dosya Var - /etc/pulse/daemon.conf "
echo "sed 1"
sudo sed -i -e 's/; resample-method = speex-float-1/resample-method = src-sinc-best-quality/g' /etc/pulse/daemon.conf
echo "sed 2"
sudo sed -i -e 's/; default-sample-format = s16le/default-sample-format = s24le/g' /etc/pulse/daemon.conf
echo "sed 3"
sudo sed -i -e 's/; default-sample-rate = 44100/default-sample-rate = 96000/g' /etc/pulse/daemon.conf
echo
else
	echo "Dosya yok"

echo creating /etc/pulse/daemon.conf 

sudo touch $filename02
echo resample-method = src-sinc-best-quality >> $filename02
echo default-sample-format = s24le >> $filename02
echo default-sample-rate = 96000 >> $filename02

echo Dosya oluşturuldu - /etc/pulse/daemon.conf 
echo ----------------------------------
fi
echo ---------------------------------------------------------------
echo ---------------------------------------------------------------
echo -----------------------------------------/etc/pulse/daemon.conf 
cat $filename02
echo ---------------------------------------------------------------
echo ---------------------------------------------------------------


pulseaudio -k
pulseaudio --start
echo ---------------------------------------------------------------
}





echo
echo ----------------------------------------------
echo ilk script from murat
echo ----------------------------------------------
echo
echo ------------------------------------------------------------- SUDO
if checker sudo == 0 ; then echo "Sudo has been installed"; 
else echo installing sudo 
sudo apt-get install sudo; fi
echo --------------------------------------------------------------SUDO
echo
echo ------------------------------------- add user murat to sudo group
echo adding murat to sudo group... 
sudo /usr/sbin/adduser murat sudo
echo ------------------------------------- add user murat to sudo group
echo


echo ------------------------------------------ LIGHTDM DISPLAY MANAGER
if checker lightdm == 0 ; then echo "lightdm has been Installed"; 
else echo installing lightdm 
sudo apt-get install lightdm; fi
echo ------------------------------------------ LIGHTDM DISPLAY MANAGER
echo
echo ------------------------------------------- CHANGE DISPLAY MANAGER
sudo /usr/sbin/dpkg-reconfigure lightdm
cat /etc/X11/default-display-manager
echo ------------------------------------------- CHANGE DISPLAY MANAGER
echo

echo ------------------------------------------------------ WHISKERMENU
if checker xfce4-whiskermenu-plugin == 0 ; then echo "xfce4-whiskermenu-plugin Installed"; 
else echo installing xfce4-whiskermenu-plugin 
sudo apt-get install xfce4-whiskermenu-plugin; fi
echo ------------------------------------------------------ WHISKERMENU
echo
echo --------------------------------------------------------- TERMINAL
if checker xfce4-terminal == 0 ; then echo "xfce4-terminal Installed"; 
else echo installing xfce4-terminal 
sudo apt-get install xfce4-terminal; fi
echo --------------------------------------------------------- TERMINAL
echo
echo ------------------------------------------------ xfce4-taskmanager
if checker xfce4-taskmanager == 0 ; then echo "xfce4-taskmanager Installed"; 
else echo installing xfce4-taskmanager 
sudo apt-get install xfce4-taskmanager; fi
echo ------------------------------------------------ xfce4-taskmanager
echo
echo ------------------------------------------------------------- TLDR
if checker tldr == 0 ; then echo "yldr Installed"; 
else echo installing tldr
sudo apt-get install tldr; fi
echo ------------------------------------------------------------- TLDR
echo
echo ------------------------------------------------------------ GEANY
if checker geany == 0 ; then echo "geany Installed"; 
else echo installing geany 
sudo apt-get install geany; fi
echo ------------------------------------------------------------ GEANY
echo
echo --------------------------------------------------------- FIREWALL
if checker ufw == 0 ; then echo "ufw Installed"; 
else echo installing ufw 
sudo apt-get install ufw; fi
echo --------------------------------------------------------- FIREWALL
echo
echo ---------- ufw status
sudo ufw status
echo ---------- ufw enable
echo this may be inactive if inactive, activate with "ufw enable" ...
sudo ufw enable
echo controlling firewall again
echo --------- ufw verbose
sudo ufw status verbose
echo --------------------------------------------------------- FIREWALL
echo


echo ----------------------------------------------------- CLEAN SYSTEM
sudo apt autoremove
sudo apt clean
echo ----------------------------------------------------- CLEAN SYSTEM
echo
echo ---------------------------------------############## kilit ekranı
01_myconf
echo ---------------------------------------############## kilit ekranı
echo
echo ---------------------------------------############## ses ayarları
daemonconf
echo ---------------------------------------############## ses ayarları
echo
echo -----------------------------------------1111111111
echo sources.list dosyasını değiştir...
echo   add "contrib non-free" after "main"
# sudo nano /etc/apt/sources.list


echo -----------------------------------------2222222222
echo whiskermenu yu panel e ekle
