######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 21 18:05:21 2007
######################################################################
QT +=  widgets
TEMPLATE = app
TARGET = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += expdelegate.h exphelper.h treedialog.h
FORMS += treedialog.ui
SOURCES += expdelegate.cpp exphelper.cpp main.cpp treedialog.cpp
