#!/bin/bash

echo ---------------------------------------------- APT_GET UPDATE
echo sistemi yenile...
sudo apt-get update
echo sistem yenilendi ----------------------------------------------



filename="/home/murat/depolnx/linux/book.txt"
set -e

function checker() { 
        which "$1" | grep -o "$1" > /dev/null &&  return 0 || return 1 
}



function 01_myconf()
{
if [ -f "$filename" ];
then

echo "Dosya Var"
else
echo "Dosya yok"
echo creating /usr/share/lightdm/lightdm.conf.d/01_myconf  

touch $filename
echo [SeatDefaults] >> $filename
echo greeter-hide-users=false >> $filename
echo allow-guest=false >> $filename
echo  >> $filename
#echo #user-session=Xfce Oturumu  >> $filename
#echo #greeter-session=LightDM GTK+ Greeter >> $filename
echo  >> $filename
echo [Seat:*] >> $filename
echo autologin-user=murat >> $filename
echo autologin-user-timeout=60 >> $filename

echo Dosya oluşturuldu
echo ----------------------------------
fi
echo /usr/share/lightdm/lightdm.conf.d/01_myconf 
echo ----------------------------------
cat $filename
echo ----------------------------------
}










echo ----------------------------------------------
echo ilk script from murat

echo ---------------------------------------------- SUDO
if checker sudo == 0 ; then echo "Sudo Installed"; 
else echo installing sudo 
sudo apt-get install sudo; fi

echo ---------------------------------------------- murat
echo adding murat to sudo group... 
sudo /usr/sbin/adduser murat sudo



echo ---------------------------------------------- CLEAN SYSTEM
if checker lightdm == 0 ; then echo "lightdm Installed"; 
else echo installing lightdm 
sudo apt-get install lightdm; fi

echo ---------------------------------------------- THEME
if checker lightdm-gtk-greeter-settings  == 0 ; then echo "lightdm-gtk-greeter-settings  Installed"; 
else echo installing lightdm-gtk-greeter-settings  
sudo apt-get install lightdm-gtk-greeter-settings ; fi

echo ---------------------------------------------- CHANGE DISPLAY MANAGER
sudo /usr/sbin/dpkg-reconfigure lightdm
echo ---------------------------------------------- DISPLAY MANAGER
echo which display manager
cat /etc/X11/default-display-manager
echo

echo ---------------------------------------------- WHISKERMENU
if checker xfce4-whiskermenu-plugin == 0 ; then echo "xfce4-whiskermenu-plugin Installed"; 
else echo installing xfce4-whiskermenu-plugin 
sudo apt-get install xfce4-whiskermenu-plugin; fi

echo ---------------------------------------------- TERMINAL
if checker xfce4-terminal == 0 ; then echo "xfce4-terminal Installed"; 
else echo installing xfce4-terminal 
sudo apt-get install xfce4-terminal; fi

echo ----------------------------------------------
if checker xfce4-taskmanager == 0 ; then echo "xfce4-taskmanager Installed"; 
else echo installing xfce4-taskmanager 
sudo apt-get install xfce4-taskmanager; fi



echo ----------------------------------------------
echo ----------------------------------------------


echo ---------------------------------------------- TLDR
if checker tldr == 0 ; then echo "yldr Installed"; 
else echo installing tldr
sudo apt-get install tldr; fi

echo ---------------------------------------------- GEANY
if checker geany == 0 ; then echo "geany Installed"; 
else echo installing geany 
sudo apt-get install geany; fi

echo ----------------------------------------------
echo ----------------------------------------------


echo ---------------------------------------------- FIREWALL
if checker ufw == 0 ; then echo "ufw Installed"; 
else echo installing ufw 
sudo apt-get install ufw; fi

echo -------------- ufw status
sudo ufw status

echo -------------- ufw enable
echo this may be inactive if inactive, activate with "ufw enable" ...
sudo ufw enable
echo controlling firewall again

echo -------------- ufw verbose
sudo ufw status verbose




echo ---------------------------------------------- CLEAN SYSTEM
sudo apt autoremove
sudo apt clean


############## kilit ekranı
01_myconf


echo ---------------------------------------------- 
#echo Sistem yazı tipini değiştirme ...
#echo    console setup yükleniyor...
#apt-get console-setup  
#sudo dpkg-reconfigure -plow console-setup 


echo ----------------------------------------------
echo sources.list dosyasını değiştir...
echo   add "contrib non-free" after "main"
# sudo nano /etc/apt/sources.list

echo **************************************************************
echo /etc/pulse/daemon.conf dosyasına 
echo
echo resample-method = src-sinc-best-quality
echo default-sample-format = s24le
echo default-sample-rate = 96000
echo
echo dosya kaydından sonra
echo pulseaudio -k
echo pulseaudio --start
